### ISSUE TITLE
Help! Getting confused over coordinates

### ISSUE THREAD

**Issue by jimmyeao** [ESPresense/ad-espresense-ips#10]
Having a tough time getting my head around which coordinates I should be using.
I just mapped it all out (or so I thought) and its stopped the app working :/

Would appreciate a set of eyes to confirm my settings or point out where I am plain wrong!
Im using the bottom left of my office as the origin (0,0)

This is my apps.yaml:

```
ESPresenseIps: 
  module: espresense-ips
  class: ESPresenseIps
  pluggins:
    - HASS
    - MQTT
  rooms:
    backhall: [0, 1.5, 0.5]
    bedroom: [3, 0.5, 0.5]
    office: [5, 1.5, 0]
    kitchen: [8, 0.5, 0.5]
    rearkitchen: [0, 0.5, 0.5]
    lounge: [2.5, 2.5, 0.5]
  devices: 
    - id: "apple:xxxx:xx-xx"
      name: "Jimmys Watch"
      timeout: 30
      away_timeout: 120
    - id: "apple:xxxx:xx-xx"
      name: "Jimmys iPhone"
      timeout: 30
      away_timeout: 120
    - id: "tile:cdxxxxxxxxxxx"
      name: "Jimmys Keys"
      timeout: 30
      away_timeout: 120
    - id: "apple:xxxx:x-xx"
      name: "Amys Watch"
      timeout: 30
      away_timeout: 120
  roomplans: 
    backhall: 
    y1: 20.0
    x1: 0.0
    y2: 22.0
    x2: 2.0
    bedroom: 
    y1: 20.0
    x1: 2.0
    y2: 23.0
    x2: 5.0
    kitchen: 
    y1: 15.0
    x1: 2.0
    y2: 19.0
    x2: 5.0
    lounge: 
    y1: 20.0
    x1: 2.0
    y2: 25.0
    x2: 5.0
    office: 
    y1: 0.0
    x1: 0.0
    y2: 1.0
    x2: 5.0
    rearkitchen: 
    y1: 2.0
    x1: 11.0
    y2: 15.0
    x2: 5.0
```

This is a rough floor plan:
![image](https://user-images.githubusercontent.com/5197831/154708353-65fd91d1-713a-4fcd-a447-622cc95dd7e8.png)
 And Im getting these error in appdaemon:
```
2022-02-18 15:06:27.092381 WARNING ESPresenseIps: ------------------------------------------------------------
2022-02-18 15:06:27.182052 WARNING AppDaemon: Suspect incorrect signature type for callback mqtt_message() in ESPresenseIps, should be f(self, event, data, kwargs) - discarding
2022-02-18 15:06:27.182435 WARNING ESPresenseIps: ------------------------------------------------------------
2022-02-18 15:06:27.182677 WARNING ESPresenseIps: Unexpected error in worker for App ESPresenseIps:
2022-02-18 15:06:27.182980 WARNING ESPresenseIps: Worker Ags: {'id': '758908665eaa4afabc2e62f590d56759', 'name': 'ESPresenseIps', 'objectid': 'd5f51b7ad6a04ed2bfc3679c6f4c7e68', 'type': 'event', 'event': 'MQTT_MESSAGE', 'function': <bound method ESPresenseIps.mqtt_message of <espresense-ips.ESPresenseIps object at 0x7f7c75a033d0>>, 'data': {'topic': 'espresense/rooms/backhall', 'wildcard': '#', 'payload': '{"id":"apple:1006:10-7","disc":"431e5eb71775","idType":35,"rssi@1m":-65,"rssi":-82,"mac":"60c6a0fbd00b","raw":3.06,"distance":3.06,"speed":0}'}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'topic': 'espresense/rooms/backhall', '__thread_id': 'thread-0'}}
2022-02-18 15:06:27.183244 WARNING ESPresenseIps: ------------------------------------------------------------
2022-02-18 15:06:27.183646 WARNING ESPresenseIps: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 950, in worker
    funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/espresense-ips.py", line 71, in mqtt_message
    roomname = room_solve(self,round(pos[0],2,),round(pos[1],2))
  File "/config/appdaemon/apps/espresense-ips.py", line 96, in room_solve
    if rooms["x1"] < float(xpos) < rooms["x2"] and rooms["y1"] < float(ypos) < rooms["y2"]:
TypeError: string indices must be integers
2022-02-18 15:06:27.183894 WARNING ESPresenseIps: ------------------------------------------------------------
```

**Comment by KuotenoAshiato** [comment]
You need to define the name in roomplans as name: '<name>'
Also there could be an issue because you're not using '-' in the roomplan section so instead of:
```
roomplans: 
    backhall: 
    y1: 20.0
    x1: 0.0
    y2: 22.0
    x2: 2.0
    bedroom: 
    y1: 20.0
    x1: 2.0
    y2: 23.0
    x2: 5.0
```
use:
```
roomplans: 
- name: backhall
  y1: 20.0
  x1: 0.0
  y2: 22.0
  x2: 2.0
- name: bedroom
  y1: 20.0
  x1: 2.0
  y2: 23.0
  x2: 5.0
```

**Comment by jimmyeao** [comment]
Wow, how did I miss that! Thanks, at least the app isn't crashing anymore :)
