### ISSUE TITLE
Error: Unexpected error loading module: /conf/apps/ad-espresense-ips/espresense-ips.py:

### ISSUE THREAD

**Issue by gravyflex** [ESPresense/ad-espresense-ips#9]
Any ideas how to resolve this error?
```
~/appdaemon$ docker-compose logs -f
Attaching to appdaemon-custom
appdaemon-custom | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
appdaemon-custom | fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
appdaemon-custom | OK: 1283 MiB in 104 packages
appdaemon-custom | Requirement already satisfied: scipy in /usr/local/lib/python3.9/site-packages (from -r /conf/apps/ad-espresense-ips/requirements.txt (line 1)) (1.7.3)
appdaemon-custom | Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from -r /conf/apps/ad-espresense-ips/requirements.txt (line 2)) (1.22.0)
appdaemon-custom | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
appdaemon-custom | WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
appdaemon-custom | You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
appdaemon-custom | 2022-01-09 14:49:16.777660 INFO AppDaemon: AppDaemon Version 4.2.0 starting
appdaemon-custom | 2022-01-09 14:49:16.777891 INFO AppDaemon: Python version is 3.9.9
appdaemon-custom | 2022-01-09 14:49:16.778132 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
appdaemon-custom | 2022-01-09 14:49:16.782568 INFO AppDaemon: Added log: AppDaemon
appdaemon-custom | 2022-01-09 14:49:16.782937 INFO AppDaemon: Added log: Error
appdaemon-custom | 2022-01-09 14:49:16.783097 INFO AppDaemon: Added log: Access
appdaemon-custom | 2022-01-09 14:49:16.783245 INFO AppDaemon: Added log: Diag
appdaemon-custom | 2022-01-09 14:49:16.806867 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
appdaemon-custom | 2022-01-09 14:49:16.972205 INFO HASS: HASS Plugin Initializing
appdaemon-custom | 2022-01-09 14:49:16.972428 INFO HASS: HASS Plugin initialization complete
appdaemon-custom | 2022-01-09 14:49:16.972663 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
appdaemon-custom | 2022-01-09 14:49:16.979690 INFO MQTT: MQTT Plugin Initializing
appdaemon-custom | 2022-01-09 14:49:16.980516 INFO MQTT: Using appdaemon_mqtt_client as Client ID
appdaemon-custom | 2022-01-09 14:49:16.981043 INFO AppDaemon: Initializing HTTP
appdaemon-custom | 2022-01-09 14:49:16.981727 INFO AppDaemon: Using 'ws' for event stream
appdaemon-custom | 2022-01-09 14:49:16.985705 INFO AppDaemon: Starting API
appdaemon-custom | 2022-01-09 14:49:16.989727 INFO AppDaemon: Starting Admin Interface
appdaemon-custom | 2022-01-09 14:49:16.990114 INFO AppDaemon: Starting Dashboards
appdaemon-custom | 2022-01-09 14:49:17.002101 INFO HASS: Connected to Home Assistant 2021.12.0
appdaemon-custom | 2022-01-09 14:49:17.023402 INFO AppDaemon: App 'ESPresenseIps' added
appdaemon-custom | 2022-01-09 14:49:17.024815 INFO AppDaemon: Found 1 total apps
appdaemon-custom | 2022-01-09 14:49:17.025203 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
appdaemon-custom | 2022-01-09 14:49:17.026256 INFO AppDaemon: Running on port 5050
appdaemon-custom | 2022-01-09 14:49:17.028347 INFO MQTT: Connected to Broker at URL <mqtt_ip>:1883
appdaemon-custom | 2022-01-09 14:49:17.050107 INFO HASS: Evaluating startup conditions
appdaemon-custom | 2022-01-09 14:49:17.050457 INFO HASS: Delaying startup for 30 seconds
appdaemon-custom | 2022-01-09 14:49:17.054855 INFO AppDaemon: Got initial state from namespace mqtt
appdaemon-custom | 2022-01-09 14:49:17.055141 INFO MQTT: MQTT Plugin initialization complete
appdaemon-custom | 2022-01-09 14:49:17.124610 INFO MQTT: Unable to decode MQTT message
appdaemon-custom | 2022-01-09 14:49:47.063785 INFO HASS: Startup condition met: hass state=RUNNING
appdaemon-custom | 2022-01-09 14:49:47.064217 INFO HASS: All startup conditions met
appdaemon-custom | 2022-01-09 14:49:47.094584 INFO AppDaemon: Got initial state from namespace default
appdaemon-custom | 2022-01-09 14:49:48.101747 INFO AppDaemon: Scheduler running in realtime
appdaemon-custom | 2022-01-09 14:49:48.104469 INFO AppDaemon: Adding /conf/apps to module import path
appdaemon-custom | 2022-01-09 14:49:48.104772 INFO AppDaemon: Adding /conf/apps/ad-espresense-ips to module import path
appdaemon-custom | 2022-01-09 14:49:48.106562 INFO AppDaemon: Loading App Module: /conf/apps/ad-espresense-ips/espresense-ips.py
appdaemon-custom | 2022-01-09 14:49:48.186441 WARNING Error: ------------------------------------------------------------
appdaemon-custom | 2022-01-09 14:49:48.186730 WARNING Error: Unexpected error loading module: /conf/apps/ad-espresense-ips/espresense-ips.py:
appdaemon-custom | 2022-01-09 14:49:48.186940 WARNING Error: ------------------------------------------------------------
appdaemon-custom | 2022-01-09 14:49:48.194257 WARNING Error: Traceback (most recent call last):
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 993, in check_app_updates
appdaemon-custom |     await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/appdaemon/utils.py", line 337, in run_in_executor
appdaemon-custom |     response = future.result()
appdaemon-custom |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
appdaemon-custom |     result = self.fn(*self.args, **self.kwargs)
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/appdaemon/app_management.py", line 784, in read_app
appdaemon-custom |     self.modules[module_name] = importlib.import_module(module_name)
appdaemon-custom |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
appdaemon-custom |     return _bootstrap._gcd_import(name[level:], package, level)
appdaemon-custom |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
appdaemon-custom |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
appdaemon-custom |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
appdaemon-custom |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
appdaemon-custom |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
appdaemon-custom |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
appdaemon-custom |   File "/conf/apps/ad-espresense-ips/espresense-ips.py", line 15, in <module>
appdaemon-custom |     from scipy.optimize import minimize
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/scipy/optimize/__init__.py", line 400, in <module>
appdaemon-custom |     from .optimize import *
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/scipy/optimize/optimize.py", line 36, in <module>
appdaemon-custom |     from ._numdiff import approx_derivative
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/scipy/optimize/_numdiff.py", line 6, in <module>
appdaemon-custom |     from scipy.sparse.linalg import LinearOperator
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/__init__.py", line 112, in <module>
appdaemon-custom |     from .dsolve import *
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/dsolve/__init__.py", line 58, in <module>
appdaemon-custom |     from .linsolve import *
appdaemon-custom |   File "/usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 11, in <module>
appdaemon-custom |     from . import _superlu
appdaemon-custom | ImportError: Error relocating /usr/local/lib/python3.9/site-packages/scipy/sparse/linalg/dsolve/_superlu.cpython-39-x86_64-linux-gnu.so: dasum_: symbol not found
appdaemon-custom | 
appdaemon-custom | 2022-01-09 14:49:48.194494 WARNING Error: ------------------------------------------------------------
appdaemon-custom | 2022-01-09 14:49:48.194688 WARNING AppDaemon: Removing associated apps:
appdaemon-custom | 2022-01-09 14:49:48.194888 WARNING AppDaemon: ESPresenseIps
appdaemon-custom | 2022-01-09 14:49:48.195648 INFO AppDaemon: App initialization complete

```

**Comment by stan69b** [comment]
I had similar results when I have multiple devices with same name in the config or a broken config file I think (even if I'm wrong, it won't hurt checking your config :) )
